//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoAbril2024GitHubEntities : DbContext
    {
        public ProyectoAbril2024GitHubEntities()
            : base("name=ProyectoAbril2024GitHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
    }
}
